name: Setup UV Environment
description: Install uv and configure caching

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        cache-local-path: "/tmp/.uv-cache"
    
    - name: uv cache
      uses: puzl-cloud/github-actions-cache@v4
      with:
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
