from datetime import datetime, timezone


GENERATED_HEADER = f"""\
# generated by https://github.com/puzl-cloud/kubesdk
#   timestamp: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}\n
"""
